# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Technology_Push_AR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Technology_Push_AR
pod 'ARCL'
end
